# Generated by Django 3.2.20 on 2023-07-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('friendly_name', models.CharField(blank=True, max_length=254, null=True)),
                ('brand_image_url', models.URLField(blank=True, max_length=1024, null=True)),
                ('brand_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
